title: Jin's DS records
description: >-
  Welcome to my space! <br>
  Have a nice day.
url: "https://whatareyoudoingz.github.io"
github: whatareyoudoingz
email: wlsdk3165@naver.com
google_analytics: <YOUR UA TOKEN>
google_site_verification:  7awHJL7hoo205m0flTMMUw1oOEDt82IIw-omHNiK64M
exclude: [README.md, Gemfile, Gemfile.lock]

comments:
  enabled: true
  repo: ChemistryX/hyde-comments
  issue-term: pathname

collections:
  pages:
    output: true
  projects:
    output: true
  studys:
    output: true
  tags:
    output: true

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:title
  - scope:
      type: projects
    values:
      layout: project
      permalink: /projects/:title
  - scope:
      type: studys
    values:
      layout: study
      permalink: /studys/:title
  - scope:
      type: tags
    values:
      layout: tag
      permalink: /tags/:title
